# Generated by Django 4.2.20 on 2026-05-22 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('media_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='profiles.modelprofile'),
        ),
    ]
