# Generated by Django 4.2.20 on 2026-06-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Si está activa, la pieza no se muestra en el perfil público.', verbose_name='oculta por moderación'),
        ),
    ]
