# Generated by Django 4.2.20 on 2026-05-31 14:53

import apps.rooms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0003_subscriptionplan_kind'),
        ('profiles', '0009_modelprofile_is_suspended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120, verbose_name='nombre para mostrar')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, help_text="Referencia general (ej: 'centro', 'sector norte'). Sin calle ni número.", max_length=80, verbose_name='sector')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(verbose_name='precio (CLP)')),
                ('price_period', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='monthly', max_length=10, verbose_name='periodo')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_payment', 'Pendiente de pago'), ('active', 'Activa'), ('expired', 'Expirada')], default='draft', max_length=16)),
                ('is_paused', models.BooleanField(default=False, verbose_name='pausado por el anfitrión')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='suspendido')),
                ('suspension_reason', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_listings', to='profiles.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='rooms.hostprofile')),
                ('plan', models.ForeignKey(blank=True, help_text='Plan elegido; define la duración al activarse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_listings', to='publications.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_receipts/')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='monto declarado (CLP)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='rooms.roomlisting')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_room_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=apps.rooms.models._private_storage, upload_to='rooms/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.roomlisting')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
