# Generated by Django 4.2.20 on 2026-05-31 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_subscriptionplan_max_listings'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomlisting',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='roomlisting',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='roomreceipt',
            name='listing',
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='active_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_subscriptions', to='publications.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='plan_featured',
            field=models.BooleanField(default=False, verbose_name='plan con destacado'),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='plan_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='habitaciones contratadas'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='destacada'),
        ),
        migrations.AddField(
            model_name='roomreceipt',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='rooms.hostprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomreceipt',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='room_receipts', to='publications.subscriptionplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Publicada'), ('expired', 'Expirada')], default='draft', max_length=16),
        ),
    ]
