# Generated by Django 4.2.20 on 2026-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomlisting_available_until_roomreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='suspendido'),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
