# Generated by Django 4.2.20 on 2026-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Usuario sin @, o link t.me/usuario.', max_length=40, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Solo dígitos en formato internacional (ej: 56912345678).', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
