# Generated by Django 4.2.20 on 2026-05-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_modelprofile_telegram_modelprofile_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'Visita'), ('contact', 'Click contacto')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='profiles.modelprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'kind', 'created_at'], name='profiles_pr_profile_941e1b_idx')],
            },
        ),
    ]
