# Generated by Django 4.2.20 on 2026-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profileevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('service', 'Servicio'), ('extra', 'Extra'), ('feature', 'Característica')], default='service', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
