# Generated by Django 4.2.20 on 2026-05-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_service_options_service_category_service_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.PositiveIntegerField(default=1, help_text='Tras aprobar el KYC, el perfil queda visible públicamente sin pago durante este número de días. Pasado ese periodo se exige una publicación active.', verbose_name='días de trial gratuito post-KYC')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
