# Generated by Django 4.2.20 on 2026-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_siteconfig_modelprofile_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Mujer'), ('trans', 'Trans'), ('male', 'Hombre')], default='female', max_length=10, verbose_name='categoría'),
        ),
    ]
