# Generated by Django 4.2.20 on 2026-05-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_modelprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
