# Generated by Django 4.2.20 on 2026-05-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_modelprofile_available_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='suspendido'),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
