# Generated by Django 4.2.20 on 2026-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_modelprofile_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='max_active_rooms_per_host',
            field=models.PositiveIntegerField(default=10, help_text='Límite global de anuncios de habitación activos simultáneos por anfitrión (anti-spam). El plan del anfitrión puede cubrir menos, pero nunca más que este tope.', verbose_name='tope de habitaciones activas por anfitrión'),
        ),
    ]
