# Generated by Django 4.2.20 on 2026-06-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profilereport_favorite_favorite_uniq_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='foto de perfil'),
        ),
    ]
