# Generated by Django 4.2.20 on 2026-06-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_modelprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Datos para transferir (banco, tipo de cuenta, número, titular, RUT, correo). Se le muestran a la modelo al elegir un plan y subir el comprobante.', verbose_name='instrucciones de pago'),
        ),
    ]
