# Generated by Django 4.2.20 on 2026-06-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_siteconfig_payment_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='support_telegram',
            field=models.CharField(blank=True, help_text='Usuario de Telegram del equipo (ej: @PortalVipSoporte) o enlace t.me/... Se muestra como botón de soporte solo a modelos y anfitriones. Sin teléfono.', max_length=120, verbose_name='Telegram de soporte'),
        ),
    ]
