# Generated by Django 4.2.20 on 2026-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_siteconfig_support_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='photo_authenticity',
            field=models.CharField(choices=[('pending', 'Por revisar'), ('none', 'Sin retoque'), ('light', 'Retoque leve'), ('heavy', 'Con retoque')], default='pending', max_length=10, verbose_name='autenticidad de fotos'),
        ),
    ]
