# Generated by Django 4.2.20 on 2026-06-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='referral_bonus_days',
            field=models.PositiveIntegerField(default=30, help_text='Días de visibilidad gratis que reciben AMBAS (la que invita y la invitada) cuando una referida se verifica.', verbose_name='días gratis por referido'),
        ),
    ]
