# Generated by Django 4.2.20 on 2026-05-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('model', 'Modelo'), ('client', 'Cliente'), ('moderator', 'Moderador'), ('admin', 'Administrador')], default='client', max_length=12),
        ),
    ]
