# Generated by Django 4.2.20 on 2026-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('model', 'Modelo'), ('client', 'Cliente'), ('host', 'Anfitrión'), ('moderator', 'Moderador'), ('admin', 'Administrador')], default='client', max_length=12),
        ),
    ]
