# Generated by Django 4.2.20 on 2026-09-24 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_session_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Acceso o copia'), ('rectification', 'Rectificación'), ('erasure', 'Eliminación/cancelación'), ('opposition', 'Oposición o retiro de consentimiento'), ('other', 'Otra solicitud de privacidad')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_review', 'En revisión'), ('completed', 'Resuelta'), ('denied', 'No procede')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=12)),
                ('terms_version', models.CharField(max_length=40)),
                ('privacy_version', models.CharField(max_length=40)),
                ('source', models.CharField(choices=[('registration', 'Registro'), ('account', 'Mi cuenta')], max_length=16)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at', '-pk'],
                'indexes': [models.Index(fields=['user', '-accepted_at'], name='users_legal_user_id_f4748b_idx')],
            },
        ),
    ]
