# Generated by Django 4.2.20 on 2026-09-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_privacyrequest_legalacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacyrequest',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
    ]
