# Generated by Django 4.2.20 on 2026-09-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verificationrequest_challenge_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='kyc_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='kyc_consent_version',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
