# Generated by Django 4.2.20 on 2026-05-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('duration_days', models.PositiveIntegerField(help_text='Días que dura la publicación activa con este plan.', verbose_name='duración (días)')),
                ('price', models.PositiveIntegerField(verbose_name='precio (CLP)')),
                ('includes_featured', models.BooleanField(default=False, help_text='Si el plan publica el anuncio como destacado.', verbose_name='incluye destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='disponible')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'duration_days'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan elegido; define la duración al activarse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='publications.subscriptionplan'),
        ),
    ]
