# Generated by Django 4.2.20 on 2026-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_subscriptionplan_publication_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='kind',
            field=models.CharField(choices=[('model_publication', 'Publicación de modelo'), ('room_listing', 'Anuncio de habitación')], default='model_publication', help_text='Para qué clasificado aplica el plan (publicación de modelo o habitación).', max_length=20, verbose_name='tipo de plan'),
        ),
    ]
