# Generated by Django 4.2.20 on 2026-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_subscriptionplan_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_listings',
            field=models.PositiveIntegerField(default=1, help_text='Solo planes de habitación: cuántos anuncios activos cubre el plan. 1 = un anuncio; >1 = bundle (varias piezas con un solo pago).', verbose_name='habitaciones incluidas'),
        ),
    ]
